[package]
name = "ecc_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version= "0.4.4", features = ["rand"] }
ec-generic = "0.1.14"
rand = "0.8.5"
sha256 = "1.1.4"
hex = "0.4.3"